name: orchid-py37
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - black
  - cudatoolkit=11.3.1
  - numpy
  - openjdk
  - perl
  - python=3.7
  - pip:
      - jsonlines
      - mypy>=0.982
      - pre-commit>=2.20
      - pytest
      - toml
      - torchvision==0.10.1
      - torch==1.9.1
      - torchaudio==0.9.1
      - transformers==4.18.0
      - types-toml
