name: orchid
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - black
  - numpy=1.21.5
  - openjdk
  - perl
  - pip>=22.1.2
  - python=3.8
  - pytorch=1.11.0
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - pip:
      - jsonlines
      - mypy>=0.982
      - pre-commit>=2.20
      - pytest
      - toml
      - transformers==4.18.0
      - types-toml
