name: orchid-py38
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - black
  - cudatoolkit=11.3.1
  - numpy=1.21.5
  - openjdk
  - perl
  - python=3.8.12
  - pytorch=1.11.0=py3.8_cuda11.3_cudnn8.2.0_0
  - torchaudio=0.11.0=py38_cu113
  - torchvision=0.12.0=py38_cu113
  - pip:
      - jsonlines
      - mypy>=0.982
      - pre-commit>=2.20
      - pytest
      - toml
      - transformers==4.18.0
      - types-toml
